### ISSUE TITLE
no issue, thanks

### ISSUE THREAD

**Issue by hedevelope** [Yusufdemirel07/Playfab#1]
can you reach me on instagram or twitter? or email that written on my website? 
hedevelope.me
Bana ulaşabilir misin kanka websitemde bilgiler mevcut. Instagram vs.

**Comment by Yusufdemirel07** [comment]
Buyur kardeşim nasıl yardımcı olabilirim ?

________________________________
Gönderen: Batuhan ***@***.***>
Gönderildi: 28 Mart 2023 Salı 10:20
Kime: Yusufdemirel07/Playfab ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [Yusufdemirel07/Playfab] no issue, thanks (Issue #1)


can you reach me on instagram or twitter? or email that written on my website?
hedevelope.me
Bana ulaşabilir misin kanka websitemde bilgiler mevcut. Instagram vs.
